import os

if 'arch' in ARGUMENTS:
    arch = ARGUMENTS['arch']
else:
    arch = os.uname()[4]

mac = ( os.uname()[0] == 'Darwin' )

src = [
    "ex.cpp",
    "op.cpp",
    "read_ex.cpp",
    "write_graphviz.cpp",
    "write_code.cpp",
    "write_code_language_cpp.cpp",
    "exmatrix.cpp",
    "exvector.cpp",
]

found_swig = os.system('which swig')

#print "sed 's/module codegen/module codegen_"+arch+"/' < codegen.i > codegen_"+arch+".i"
#os.system( "sed 's/module codegen/module codegen_"+arch+"/' < codegen.i > codegen_"+arch+".i" )
#Command( "codegen_"+arch+".i", "codegen.i", "sed 's/module codegen/module codegen_"+arch+"/' < $SOURCE > $TARGET" )

SharedLibrary(
    'codegen',
    src + [ [ "codegen_wrap.cc", "codegen.i" ][found_swig==0] ],
    SWIGFLAGS = "-python -c++",
    SHLIBPREFIX = "#_",
    SHLIBSUFFIX = ".so",
    LINKFLAGS = "-flat_namespace -undefined suppress" * mac,
    CPPFLAGS = os.popen("python-config --includes","r").read().strip(),
    SHOBJSUFFIX = "_" + arch + ".o"
)
