Import('env')

src = [
    'amd_aat.c',
    'amd_1.c',
    'amd_2.c',
    'amd_dump.c',
    'amd_postorder.c',
    'amd_post_tree.c',
    'amd_defaults.c',
    'amd_order.c',
    'amd_control.c',
    'amd_info.c',
    'amd_valid.c',
]

# libi = env.Library('LMT_amd_i', src, CPPFLAGS = '-DDINT' , src_suffix = '.oi' )
# libl = env.Library('LMT_amd_l', src, CPPFLAGS = '-DDLONG', src_suffix = '.ol' )

lib = env.Library('LMT_amd', src, CC='gcc', CPPFLAGS = '-DDINT -ILMT/include/amd' )

Return('lib')
