
namespace LMT {

/**
    Used to concatenate 2 vectors
*/
template<class V0,bool v0_const=true,class V1=void,bool v1_const=true,class V2=void,bool v2_const=true,class V3=void,bool v3_const=true> struct VecAppend {};

template<class V0,bool v0_const,class V1,bool v1_const> struct IsVecOp<VecAppend<V0,v0_const,V1,v1_const> > { typedef int T; };


template<class V0,bool v0_const,class V1,bool v1_const,int ss>
class Vec<VecAppend<V0,v0_const,V1,v1_const>,ss,int> {
public:
    template<unsigned n> struct SubType {
        typedef typename AlternativeOnType< (n >= V0::nb_sub_type),
            typename V0::template SubType<n>::T,
            typename V1::template SubType<n-V0::nb_sub_type>::T
        >::T T;
    };
    static const unsigned nb_sub_type = (
        V0::nb_sub_type==1 && V1::nb_sub_type==1 ?
        2-AreSameType<typename V0::template SubType<0>::T,typename V1::template SubType<0>::T>::res : V0::nb_sub_type==1+V1::nb_sub_type
    );
    static const unsigned static_size = V0::static_size + V1::static_size;
    static const bool fixed_size = V0::fixed_size && V1::fixed_size;
    typedef typename V0::template SubType<0>::T T0;
    
    Vec(const V0 &vv0,const V1 &vv1) { v0.val=&vv0; v1.val=&vv1; }
    Vec(const V0 &vv0,      V1 &vv1) { v0.val=&vv0; v1.val=&vv1; }
    Vec(      V0 &vv0,const V1 &vv1) { v0.val=&vv0; v1.val=&vv1; }
    Vec(      V0 &vv0,      V1 &vv1) { v0.val=&vv0; v1.val=&vv1; }

    unsigned size() const { return v0.val->size() + v1.val->size(); }

    T0 operator[](unsigned i) const { if (i<v0.val->size()) return (*v0.val)[i]; return (*v1.val)[i-v0.val->size()]; }
    T0 &operator[](unsigned i) { if (i<v0.val->size()) return (*v0.val)[i]; return (*v1.val)[i-v0.val->size()]; }
    
    PtrConstIf<V0,v0_const> v0;
    PtrConstIf<V1,v1_const> v1;
};

template<class V0,class V1> Vec<VecAppend<V0,true ,V1,true > > appended( const V0 &v0, const V1 &v1 ) { return Vec<VecAppend<V0,true ,V1,true > >(v0,v1); }
template<class V0,class V1> Vec<VecAppend<V0,true ,V1,false> > appended( const V0 &v0,       V1 &v1 ) { return Vec<VecAppend<V0,true ,V1,false> >(v0,v1); }
template<class V0,class V1> Vec<VecAppend<V0,false,V1,true > > appended(       V0 &v0, const V1 &v1 ) { return Vec<VecAppend<V0,false,V1,true > >(v0,v1); }
template<class V0,class V1> Vec<VecAppend<V0,false,V1,false> > appended(       V0 &v0,       V1 &v1 ) { return Vec<VecAppend<V0,false,V1,false> >(v0,v1); }


  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { apply(*v.v0.val,op); apply(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { apply(*v.v0.val,op); apply(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { apply(*v.v0.val,op); apply(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { apply(*v.v0.val,op); apply(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { apply(*v.v0.val,op,p0); apply(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { apply(*v.v0.val,op,p0,p1); apply(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply(*v.v0.val,op,p0,p1,p2); apply(*v.v1.val,op,p0,p1,p2); }

  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi); apply(*v.v1.val,opi); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi); apply(*v.v1.val,opi); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi); apply(*v.v1.val,opi); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi); apply(*v.v1.val,opi); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0); apply(*v.v1.val,opi,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1); apply(*v.v1.val,opi,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,1> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_wi(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { OpWithIncrement<Op,0> opi(op); apply(*v.v0.val,opi,p0,p1,p2); apply(*v.v1.val,opi,p0,p1,p2); }

  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { return find(*v.v0.val,op) || find(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op) { return find(*v.v0.val,op) || find(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { return find(*v.v0.val,op) || find(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op) { return find(*v.v0.val,op) || find(*v.v1.val,op); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0) { return find(*v.v0.val,op,p0) || find(*v.v1.val,op,p0); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1) { return find(*v.v0.val,op,p0,p1) || find(*v.v1.val,op,p0,p1); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline bool find(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { return find(*v.v0.val,op,p0,p1,p2) || find(*v.v1.val,op,p0,p1,p2); }

  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1,const TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,const TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,const TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,const Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(const Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }
  template<class V0,bool const_v0,class V1,bool const_v1,int s,class Op,class TP0,class TP1,class TP2> inline void apply_range(Vec<VecAppend<V0,const_v0,V1,const_v1>,s,int> &v,int from,int to,Op& op,TP0 &p0,TP1 &p1,TP2 &p2) { apply_range(*v.v0.val,op,from,to); from-=min(from,v.v0.val->size()); to-=min(to,v.v0.val->size()); apply_range(*v.v1.val,op,from,to); }

} // namespace LMT
